stages:
  train:
    cmd: python -m src.scripts.train
    deps:
      - src/scripts/train.py
      - src/
      - data/raw/train.csv
      - data/raw/test.csv
    params:
      - model
      - paths
      - features
      - data
    outs:
      - models/model.pkl