mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "titanic_classifier_experiment"  # Use your model or project name
  artifact_location: "mlruns"  # Default MLflow local folder
  register_model: true
  model_registry: "models/registry"

grid_search:
  random_forest:
    n_estimators: [100, 200, 300]
    max_depth: [10, 20, 30, null]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
  xgboost:
    n_estimators: [100, 200, 300]
    max_depth: [3, 5, 7, 9]
    learning_rate: [0.01, 0.05, 0.1]
    subsample: [0.8, 0.9, 1.0]
    colsample_bytree: [0.8, 0.9, 1.0]